# Generated by Django 3.2.10 on 2021-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
