# Generated by Django 3.2.10 on 2021-12-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0002_chambre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Client',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concerne', models.IntegerField(max_length=9, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambre.client')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periode_reservation', models.DateTimeField(auto_now_add=True, null=True)),
                ('Chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambre.chambre')),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambre.client')),
                ('Reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambre.reservation')),
            ],
        ),
    ]
