# Generated by Django 3.2.10 on 2021-12-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0003_auto_20211228_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id_concerne',
        ),
    ]
