# Generated by Django 3.2.10 on 2021-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0005_auto_20211228_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Client',
            field=models.ManyToManyField(to='chambre.Client'),
        ),
    ]
