# Generated by Django 3.2.10 on 2021-12-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0006_auto_20211228_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='etage',
            field=models.CharField(choices=[('etage1', 'etage1'), ('etage2', 'etage2'), ('etage3', 'etage3'), ('etage4', 'etage5')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambre.client'),
        ),
    ]
