# Generated by Django 3.2.10 on 2021-12-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0007_auto_20211228_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Client',
            new_name='client',
        ),
    ]
