# Generated by Django 3.2.10 on 2022-01-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0008_rename_client_reservation_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_d',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_f',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
