# Generated by Django 3.2.10 on 2022-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0010_alter_reservation_date_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_d',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_d',
            field=models.DateTimeField(null=True),
        ),
    ]
