# Generated by Django 3.2.10 on 2022-01-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0011_auto_20220105_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='Periode_reservation',
        ),
        migrations.AddField(
            model_name='planning',
            name='date_d',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='date_f',
            field=models.DateTimeField(null=True),
        ),
    ]
