# Generated by Django 3.2.10 on 2022-01-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0012_auto_20220105_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date_d',
            new_name='date',
        ),
    ]
