# Generated by Django 3.2.10 on 2022-01-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0013_rename_date_d_client_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
