# Generated by Django 3.2.10 on 2022-01-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0014_chambre_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='nom',
            new_name='nom_ch',
        ),
    ]
