# Generated by Django 3.2.10 on 2022-01-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0016_auto_20220105_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_d_r',
            new_name='date_dedutR',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_f_r',
            new_name='date_finR',
        ),
    ]
