# Generated by Django 3.2.10 on 2022-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0017_auto_20220105_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chambre',
            name='paice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
