# Generated by Django 3.2.10 on 2022-02-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0018_auto_20220208_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='dispo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='paice',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
