# Generated by Django 3.2.10 on 2022-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0019_auto_20220208_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
