# Generated by Django 3.2.10 on 2022-02-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0020_alter_chambre_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Chambre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambre.chambre'),
        ),
    ]
